### ISSUE TITLE
Question about the project name

### ISSUE THREAD

**Issue by marwanpro** [microsoft/lain#3]
Is the project name (_lain_) a reference to the anime character [Lain Iwakura](https://en.wikipedia.org/wiki/Serial_Experiments_Lain) ?

![](https://upload.wikimedia.org/wikipedia/en/3/32/Serial_Experiments_Lain_DVD_vol_1.jpg)

**Comment by osu** [comment]
gay

**Comment by landaire** [comment]
It's a coincidence
