### ISSUE TITLE
Example Usage code doesn't work

### ISSUE THREAD

**Issue by kenta7777** [microsoft/lain#4]
[Example Usage code](https://github.com/microsoft/lain#example-usage) doesn't work.
If this code is compiled, An compile error which points out no argument for a method named `hexdump` is occurred.

**Comment by kenta7777** [comment]
I think the argument expected for `hexdump` is `&serialized_data`.

**Comment by landaire** [comment]
Yeah, it should be `&serialized_data`. Looks like I made a copy/paste error. Thanks for pointing this out, I'll fix it soon.
